### ISSUE TITLE
Problems compiling Aitk

### ISSUE THREAD

**Issue by gogonapel** [t0kt0ckus/Aitk#1]
Hi!

I made a new Android Eclipse project and added all the files from the Aitk directory.

I compiled both libaitk.jar and libsusrv.jar for android platform 16 which is the api that the Jelly Bean on the test android phone uses and added them to the libs folder. Here are the errors I get, what could be the issue ? Thank you!

05-04 15:25:32.160: D/ActivityThread(11879): setTargetHeapUtilization:0.25
05-04 15:25:32.160: D/ActivityThread(11879): setTargetHeapIdealFree:8388608
05-04 15:25:32.160: D/ActivityThread(11879): setTargetHeapConcurrentStart:2097152
05-04 15:25:32.290: D/TailFragment(11879): onCreate()
05-04 15:25:32.290: D/TailFragment(11879): onCreateView()
05-04 15:25:32.300: D/SmserActivity(11879): onCreate()
05-04 15:25:32.310: W/dalvikvm(11879): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lorg/openmarl/susrv/LibSusrv;
05-04 15:25:32.310: D/AndroidRuntime(11879): Shutting down VM
05-04 15:25:32.310: W/dalvikvm(11879): threadid=1: thread exiting with uncaught exception (group=0x40e51438)
05-04 15:25:32.310: E/AndroidRuntime(11879): FATAL EXCEPTION: main
05-04 15:25:32.310: E/AndroidRuntime(11879): java.lang.ExceptionInInitializerError
05-04 15:25:32.310: E/AndroidRuntime(11879):    at com.example.smertest.ProcessChoiceFragment.refreshProcessList(ProcessChoiceFragment.java:54)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at com.example.smertest.ProcessChoiceFragment.onStart(ProcessChoiceFragment.java:44)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.app.Fragment.performStart(Fragment.java:1570)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1017)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:1809)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.app.Activity.performStart(Activity.java:5200)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2087)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2139)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.app.ActivityThread.access$700(ActivityThread.java:143)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.os.Handler.dispatchMessage(Handler.java:99)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.os.Looper.loop(Looper.java:137)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at android.app.ActivityThread.main(ActivityThread.java:4963)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at java.lang.reflect.Method.invokeNative(Native Method)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at java.lang.reflect.Method.invoke(Method.java:511)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at dalvik.system.NativeStart.main(Native Method)
05-04 15:25:32.310: E/AndroidRuntime(11879): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load susrv: findLibrary returned null
05-04 15:25:32.310: E/AndroidRuntime(11879):    at java.lang.Runtime.loadLibrary(Runtime.java:365)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at java.lang.System.loadLibrary(System.java:535)
05-04 15:25:32.310: E/AndroidRuntime(11879):    at org.openmarl.susrv.LibSusrv.<clinit>(LibSusrv.java:148)
05-04 15:25:32.310: E/AndroidRuntime(11879):    ... 20 more
05-04 15:25:32.320: I/dalvikvm(11879): Rejecting re-init on previously-failed class Lorg/openmarl/susrv/LibSusrv; v=0x0
05-04 15:25:32.420: W/dalvikvm(11879): threadid=11: thread exiting with uncaught exception (group=0x40e51438)
05-04 15:25:32.420: I/Process(11879): Sending signal. PID: 11879 SIG: 9

**Comment by gogonapel** [comment]
I managed to get it going . Apparently I didn't also paste the libs folder from libsusrv-master after compilation into the LIBS folder of the project directory but now I have a new pb. 

The app loads ok I can select the processes and the libraries to inject but the Hijack button is deactivated. Apparently public void onContextReady(AitkContext ctx) {  doesn't get called back. What am I doing wrong? Thank you!
